project:
  type: website

website:
  title: "ryankellysite"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - software.qmd
      - thoughts.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/RP_Kelly98
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



