on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check for changes in specific files
        id: file-check
        uses: dorny/paths-filter@v2
        with:
          list-files: 'shell'
          filters: |
            notebook:
              - '**/*.ipynb'
              - '**/*.csv'  # Add paths to data files or other dependencies as needed

      - name: Install Python dependencies
        if: steps.file-check.outputs.notebook == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render and Publish
        if: steps.file-check.outputs.notebook == 'true'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          publish: true  # Ensure to enable publishing if the notebook or data has changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render without Execution
        if: steps.file-check.outputs.notebook != 'true'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          execute: false  # This will render without executing the notebooks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
